### ISSUE TITLE
1.9.4 4.0.3 overrides StimmedCow:NoMoreRecipeConflict Mod

### ISSUE THREAD

**Issue by kreezxil** [blay09/CraftCraft#18]
The other mod is found at http://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict and provides an arrow on crafting grids to allow you to cycle between possible outputs when the same recipe is registered more than once. 

Your mod is overriding that behavior.

**Comment by BlayTheNinth** [comment]
CraftingCraft isn't overriding anything at all, it just adds a bunch of new crafting tables. The vanilla crafting table is not touched.

**Comment by kreezxil** [comment]
Hmm, thought it was, well close this while I try to pinpoint my issue.

-----Original Message-----
