### ISSUE TITLE
Crafting table GUIs not opening when Water Strainer mod is installed

### ISSUE THREAD

**Issue by tikisri** [blay09/CraftCraft#24]
Stone , Netherrack, and the Crafting Table frame items are not functional when I right click with an open hand  to use them as a crafting table. not functioning when right clicking with an item. either

**Comment by BlayTheNinth** [comment]
Are you in Adventure Mode or have another mod installed that is doing some form of permission handling? It's working just fine here.

**Comment by tikisri** [comment]
Woll need to contact vaygrim to get premission to release mod list to you
because pack is wip pls standby contact email?

**Comment by tikisri** [comment]
http://imgur.com/a/wnh3P -- Picture of Mod Folder, I don't know enough about of modding to know if any of the mods have permissions handling

**Comment by BlayTheNinth** [comment]
I don't know every mod in there so I can't tell you what might be stopping you from using the tables, but it does not happen for anyone else. Maybe you're in the spawn area of a server or something. Whatever it is, it's not an issue on this mod's side.

**Comment by BlayTheNinth** [comment]
nvm. Just got another report about this. >_<

**Comment by SockWulf** [comment]
I had the same issue, so tested the mods that both I and the OP use. It turns out that there's some kind of conflict with the Water Strainer mod.

**Comment by BlayTheNinth** [comment]
Thanks, I'll have a look at that mod.

**Comment by BlayTheNinth** [comment]
It's actually putting the error in the log as well.

http://pastebin.com/YtHmJPGA

Reported here: https://minecraft.curseforge.com/projects/water-strainer#c53

I'll add an additional sanity check for the value passed by the recipe for the next version.
