### ISSUE TITLE
No More More Recipe Conflict duplicates recipes on each server start

### ISSUE THREAD

**Issue by sandalle** [blay09/CraftCraft#28]
I have not tested with other Minecraft versions, but for Minecraft 1.12.2 with NoMoreRecipeConflict 0.9 (1.12), every time I start my server (I have not tested client only), the config/recipes/ folder has all current recipes duplicated and named to a new alternate version (_alt_#). Next startup, yet another setup of full duplicates (_alt_alt_#). Each time I start my server I remove the config/recipes/ folder to keep the list manageable.

Minecraft: 1.12.2
Forge Mod Loader: 1.12.2-14.23.1.2556
NoMoreRecipeConflict: 0.9 (1.12)

**Comment by BlayTheNinth** [comment]
How is that related to this mod?

**Comment by sandalle** [comment]
They started showing up after adding this mod, I thought, and they're the alternate recipes which show up in the Conflict Button configured in recipehandler.cfg .

**Comment by BlayTheNinth** [comment]
This should be reported to NoMoreRecipeConflict, I can't imagine anything here that would normally cause such behaviour.

**Comment by sandalle** [comment]
My apologies @blay09 , I searched for "stimmedcow : NoMoreRecipeConflict GitHub" and it took me to CraftingCraft, so I assumed you somehow had a hand in No More Recipe Conflict as there were no obvious issue trackers for it on CurseForge, but now see it was a discussion about possible recipe conflicts. :/
