### ISSUE TITLE
[Request] Inventory Crafting Alternative

### ISSUE THREAD

**Issue by XvBUSHvX** [blay09/CraftCraft#30]
I am designing a modpack, and one of the concepts for the pack is that most recipes will require the larger 3x3 crafting matrix. And that simpler items will be crafted in the standard 3x3 crafting matrix. I had hopes that CraftingCraft provided a feature of replacing the 2x2 matrix with the 3x3 matrix with the "Inventory Crafting" item. I hadn't realized that it's simply a different interface for the "Portable Crafting" Item. 

I have seen other mods that provide the feature I am requesting. However they either come with a number of features completely over power, out of scope, or don't function with CraftingTweaks. 

I would like to request, if possible, a config setting that would replace the 2x2 matrix in the player inventory with a 3x3 matrix. So at world start players would have access to the 3x3 matrix. It would be preferable if this expanded the size of the matrix at the current location, go ahead and remove that book for space you said it right in the config for CraftTweaker anyways lol. However, if for any reason you are not able to, or not inclined to do so, if you could make "Inventory Crafting" feature in the players native inventory, without the need of an item, though inconvenient would be appreciated all the same. 

Thank you for your work and contributions to the community, I look forward to your decision.

**Comment by BlayTheNinth** [comment]
This would be a pretty intrusive change for a content-mod such as CraftingCraft, I do not think it fits here. 

The bigger problem is though that even with the book button gone, there's not enough space in the GUI without resulting in something ugly like this:
![image](https://user-images.githubusercontent.com/1933180/44516714-17554600-a6c6-11e8-9cdf-476fe94d8a79.png)

This does not follow the GUI standard set by Vanilla, which uses a crafting arrow to indicate the result slot. 

Something like this could work, but still looks kinda cramped and gives the impression that the shield slot is somehow part of the crafting grid:

![image](https://user-images.githubusercontent.com/1933180/44517117-18d33e00-a6c7-11e8-8e7c-a20b8050b590.png)

And either of them would likely result in incompatibilities with other mods that add buttons to the inventory, expecting there to be empty space. 

If there's really no mod currently providing just the 3x3-inventory-grid feature I may try and make one at some point, but it will be separate, and not part of CraftingCraft.

The modder who made https://minecraft.curseforge.com/projects/inventory-crafting-grid is still active, so if you show interest he may be willing to port it to Minecraft 1.12.

**Comment by XvBUSHvX** [comment]
That's fair, thank you for your time and considerations. It has given be a couple of things to consider as I do intend to include at least one mod that does add a button. This may be something better suited to be included in it's own tab. I'll visit the developer you mentioned above and run a couple of ideas past them.
