### ISSUE TITLE
[1.14.x] Reintroduce JEI support

### ISSUE THREAD

**Issue by BlayTheNinth** [blay09/CraftCraft#32]

**Comment by leeterry** [comment]
See, I was just gonna let you know that in 1.14.4 although JEI shows the recipes from this mod it is not recognizing the modded tables ui as tables and therefore it is not possible to have it to add the items to the crafting grid for you (the + button is not even showing like it does when you are at a crafting bench). I assume that is what this is about but figured I should mention it anyway just in case I am wrong.
