### ISSUE TITLE
1.14.4 Server Crash

### ISSUE THREAD

**Issue by Wissi** [blay09/CraftCraft#33]
Awesome mod. 
Works great in SP and in Server if just this mod and Crafting Tweaks.
But there seems to be a mod conflict that crashes server when we add your mod to an existing working modpack.
Full crash log [here](https://gist.github.com/Wissi/4ae37ff8820d4446751bc8ecaf2d8487).
We found at least incompatibility with:
[Corail Woodcutter](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
We'll try to see which other mods it has conflict with and report back.

Using:
Forge_28.0.83.jar
CraftingCraft_1.14.4-7.1.3.jar
corail_woodcutter-1.0.6-1.14.4.jar

Thanks.

**Comment by BlayTheNinth** [comment]
The crash log indicates a failure during initialization, so there should be another crashlog further up, which caused the event bus to shutdown.

**Comment by Wissi** [comment]
Anything on your end that could be done to avoid this?
You have link to the full log.
If you need anything from us just let me know.
Thanks.

**Comment by BlayTheNinth** [comment]
Sorry, by "another crashlog further up" I meant an exception inside the latest.log.

Corail looked into this and found CraftingCraft is having issues starting up on servers. It's odd that it worked for you with just CraftingCraft, as it should have generally not worked on dedicated servers, but I've uploaded a new version of CraftingCraft that fixes the crash on server startups.
