### ISSUE TITLE
Support for REI transfer button

### ISSUE THREAD

**Issue by williamhatcher** [blay09/CraftCraft#44]
Please add integrations for REI/JEI to allow the little plus button to bring items into the crafting table. Here's REI's GitHub: https://github.com/shedaniel/RoughlyEnoughItems

**Comment by BlayTheNinth** [comment]
It looks like REI only offers a common API artifact for Architectury-based projects.

Unless ModDevGradle adds support for remapping dependencies, or REI offers a mojmap artifact, supporting it would mean keeping and maintaining three copies of the same code, which is not something I'm ready to do.
