### ISSUE TITLE
i cant craft the crafting inventory and the other thing for inventory crafting

### ISSUE THREAD

**Issue by NatureisticProtogen** [blay09/CraftCraft#53]
### Minecraft Version

1.20.x

### Mod Loader

Fabric

### Mod Loader Version

newest 

### Mod Version

16.0.0

### Balm Version

new one

### Describe the Issue

it says it in the title

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Cannot reproduce + lack of info in report
