### ISSUE TITLE
Overwrite default inventory bind

### ISSUE THREAD

**Issue by R0gyman** [blay09/CraftCraft#55]
can you add a option to where when you have a crafting table in your inventory it will overwrite the default open inventory button?
it would make it to where we wouldn't have to bind anything and there wont be 2 separate inventory buttons
handy mod btw

**Comment by BlayTheNinth** [comment]
The Inventory Crafting Table isn't a full-fledged inventory screen, so doing this would prevent the user from accessing their inventory at all.
