### ISSUE TITLE
1.8.9 version don't save inventory.

### ISSUE THREAD

**Issue by zedner** [blay09/CraftCraft#7]
tooltip in stone crafting table says that it keeps items after closing but when i close it, it places those items back items to my inventory. didn't test it on nether table

**Comment by scyfar** [comment]
Can confirm this. The nether and table frame versions have the same behaviour.

When you put items in either the stone, nether or table frame version and close it, the items land in your inventory (most of the time) or get lost.

My experience is that you sometimes get the items back immediately when you close the crafting table. Most of the time you do not get them back immediately but when you open another inventory like a chest (not the player inventory). If you take too long to do so or you change your player inventory in between you do not get the items back.

**Version**
CraftingCraft: mc1.8.9-2.0.6
Forge: 1.8.9-forge1.8.9-11.15.0.1697

**Comment by BlayTheNinth** [comment]
Uhh..yeah. Apparently I specifically added code that puts it back into the inventory. I have no idea why I did that. Will be fixed in the version I'm uploading later today.

**Comment by BlayTheNinth** [comment]
Fix is up on CurseForge and awaiting approval now.

**Comment by scyfar** [comment]
I can confirm that it is now working properly for all types. :+1:
